### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by ram-you** [zeye-ru/zeye-server#2]
Hi, 
I wanted to ask you if your solution is production ready (server + client) and how to compare it against Edumeet solution (https://github.com/edumeet/edumeet - 528 github starred)?
Thank you.

**Comment by stasoft91** [comment]
Hi, I guess it is as production ready as any other one-dude-was-bored-and-made-something open source solution :)
Regarding edumeet - I made this package because to me was easier to build a clean foundation to stack features on top of it, than to cut down all the unnecessaries from them. Still, surely, edumeet is much more complete and more maintained.

**Comment by ram-you** [comment]
Thank you very much for your answer.
What I wanted to know, according to you, are there any projects that use your solution in production mode.
What led me to ask you this question is the fact that I have looked a bit at your code and found it to be clear and well written.

**Comment by stasoft91** [comment]
Ah, of course, https://zeye.ru
